### PR TITLE
Remove C++ files

### PR DESCRIPTION
**Pull request by davidmikulis**
Remove files with the previous C++ code

### CODE REVIEW

**Review by robomoto — CHANGES_REQUESTED** [review]
the empty __init__.py file is required for being able to import classes from other python files.  All other files in here can be removed.

**Comment by davidmikulis** [comment]
Hmmm why is the __init__.py required? The other directories are importing Python files fine without it.

**Comment by davidmikulis** [comment]
This StackOverflow post inidcates the __init__.py was necessary prior to Python 3.3 (2012)
https://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3-3

**Review by robomoto — APPROVED** [review]
Oh!  Okay then.  Approved!  Thanks for helping me clear out an archaic practice. 👍

**Pull request merged**
